apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-k8s-app
  template:
    metadata:
      labels:
        app: cicd-k8s-app
    spec:
      containers:
        - name: cicd-k8s-container
          image: cicd-k8s-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80